 version: "3.8"
 services:
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    command: bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: Iker
      MYSQL_PASSWORD: p@ssw0rd
